install:
  - yes | sudo add-apt-repository ppa:canonical-qt5-edgers/qt5-daily
  - sudo apt-get update
  - sudo apt-get install qtchooser qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev qt5widgets5 libqt5sql5-sqlite libqt5sql5-sqlite

script:
  - qtchooser -run-tool=qmake -qt=qt5 src/Langunator.pro
  - make