install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qt5-qmake libqt5webkit5-dev libqt5multimediawidgets5 qt4-dev-tools qt4-qmake qt4-qtconfig

script:
  - qmake cpp/Langunator.pro
  - make